display recipe card
TheTiiiim/evening-planner pull request #5
Opened 2021-02-03 03:29 UTC by TheTiiiim

I reused the function to display data to the movie card and adjust it to take more options, I also made it a global object by attaching it to the `window` object, that was the only way I've found to use it across files.

2021-02-03 17:09 UTC, hannamunoz approved these changes

2021-02-03 17:21 UTC, hannamunoz commented on assets/js/recipe.js
> +            link: result.spoonacularSourceUrl,
Do we want to use the spoontacular URL or the sourceUrl? They both work, not sure which would be a better user experience

2021-02-03 17:23 UTC, hannamunoz commented on assets/js/recipe.js
> +        };
Do we want to render more than one recipe here and let the user choose or leave as is?

2021-02-03 17:28 UTC, hannamunoz commented on index.html
> +							<p></p>
We might want to change the background color of the card because it looks like where they link text, it's showing up white.
<img width="588" alt="Screen Shot 2021-02-03 at 12 26 06 PM" src="https://user-images.githubusercontent.com/74687471/106785401-591aa280-661b-11eb-973c-4d48e00e2cbb.png">

2021-02-03 17:31 UTC, hannamunoz requested changes
Left a few comments to review

2021-02-03 20:48 UTC, TheTiiiim commented on assets/js/recipe.js
> +            link: result.spoonacularSourceUrl,
I looked at both and went with the spoonacular link for sake of uniformity

2021-02-03 21:25 UTC, Taylorgonz approved these changes

2021-02-03 21:25 UTC, Taylorgonz commented on assets/js/recipe.js
> +        };
maybe we could render 3 and users could choose whichever they like best

2021-02-03 21:25 UTC, Taylorgonz commented on index.html
> +							<p></p>
do that or just change link color, I'll play around with how it looks

2021-02-03 21:55 UTC, TheTiiiim commented on index.html
> +							<p></p>
I don't have much control over how links look, they put html tags into their summary string

2021-02-03 22:01 UTC, TheTiiiim commented on index.html
> +							<p></p>
closer inspection shows this is coming from our style.css file, I did a search and the only anchor tags exist within our result cards, so I may just change that

2021-02-03 22:18 UTC, Taylorgonz commented on index.html
> +							<p></p>
oh that's from the header links feel free to change it for now.

2021-02-04 00:07 UTC, SprengerV approved these changes

2021-02-04 00:09 UTC, hannamunoz approved these changes

2021-02-04 00:17 UTC, SprengerV approved these changes
Looks good.

2021-02-04 00:43 UTC, merged